using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Text.RegularExpressions;

namespace py2km.api
{
    public class Converter
    {
		public static string PinyinToKwikMandarin(string input)
		{
			var dict = new Dictionary<string, string>
			{
				{"fei", "fëi"},
				{"fēi", "f¡i"},
				{"féi", "f¢i"},
				{"fěi", "f£i"},
				{"fèi", "f¤i"},
				{"hei", "hëi"},
				{"hēi", "h¡i"},
				{"héi", "h¢i"},
				{"hěi", "h£i"},
				{"hèi", "h¤i"},
				{"lei", "lëi"},
				{"lēi", "l¡i"},
				{"léi", "l¢i"},
				{"lěi", "l£i"},
				{"lèi", "l¤i"},
				{"lian", "liën"},
				{"liān", "li¡n"},
				{"lián", "li¢n"},
				{"liǎn", "li£n"},
				{"liàn", "li¤n"},
				{"lie", "lië"},
				{"liē", "li¡"},
				{"lié", "li¢"},
				{"liě", "li£"},
				{"liè", "li¤"},
				{"lüe", "luië"},
				{"lüē", "lui¡"},
				{"lüé", "lui¢"},
				{"lüě", "lui£"},
				{"lüè", "lui¤"},
				{"lü", "luiy"},
				{"lǖ", "luīy"},
				{"lǘ", "luíy"},
				{"lǚ", "luǐy"},
				{"lǜ", "luìy"},
				{"mei", "mëi"},
				{"mēi", "m¡i"},
				{"méi", "m¢i"},
				{"měi", "m£i"},
				{"mèi", "m¤i"},
				{"mian", "miën"},
				{"miān", "mi¡n"},
				{"mián", "mi¢n"},
				{"miǎn", "mi£n"},
				{"miàn", "mi¤n"},
				{"mie", "mië"},
				{"miē", "mi¡"},
				{"mié", "mi¢"},
				{"miě", "mi£"},
				{"miè", "mi¤"},
				{"nei", "nëi"},
				{"nēi", "n¡i"},
				{"néi", "n¢i"},
				{"něi", "n£i"},
				{"nèi", "n¤i"},
				{"nian", "niën"},
				{"niān", "ni¡n"},
				{"nián", "ni¢n"},
				{"niǎn", "ni£n"},
				{"niàn", "ni¤n"},
				{"nü", "nuiy"},
				{"nǖ", "nuīy"},
				{"nǘ", "nuíy"},
				{"nǚ", "nuǐy"},
				{"nǜ", "nuìy"},
				{"nüe", "nuië"},
				{"nüē", "nui¡"},
				{"nüé", "nui¢"},
				{"nüě", "nui£"},
				{"nüè", "nui¤"},
				{"ri", "re"},
				{"rī", "rē"},
				{"rí", "ré"},
				{"rǐ", "rě"},
				{"rì", "rè"},
				{"si", "se"},
				{"sī", "sē"},
				{"sí", "sé"},
				{"sǐ", "sě"},
				{"sì", "sè"},
				{"shei", "shëi"},
				{"shēi", "sh¡i"},
				{"shéi", "sh¢i"},
				{"shěi", "sh£i"},
				{"shèi", "sh¤i"},
				{"shi", "she"},
				{"shī", "shē"},
				{"shí", "shé"},
				{"shǐ", "shě"},
				{"shì", "shè"},
				{"wei", "wëi"},
				{"wēi", "w¡i"},
				{"wéi", "w¢i"},
				{"wěi", "w£i"},
				{"wèi", "w¤i"},
				{"ye", "yë"},
				{"yē", "y¡"},
				{"yé", "y¢"},
				{"yě", "y£"},
				{"yè", "y¤"},
				{"yan", "yën"},
				{"yān", "y¡n"},
				{"yán", "y¢n"},
				{"yǎn", "y£n"},
				{"yàn", "y¤n"},
				{"yu", "yuiy"},
				{"yū", "yuīy"},
				{"yú", "yuíy"},
				{"yǔ", "yuǐy"},
				{"yù", "yuìy"},
				{"yuan", "yuën"},
				{"yuān", "yu¡n"},
				{"yuán", "yu¢n"},
				{"yuǎn", "yu£n"},
				{"yuàn", "yu¤n"},
				{"yue", "yuë"},
				{"yuē", "yu¡"},
				{"yué", "yu¢"},
				{"yuě", "yu£"},
				{"yuè", "yu¤"},
				{"yun", "yuin"},
				{"yūn", "yuīn"},
				{"yún", "yuín"},
				{"yǔn", "yuǐn"},
				{"yùn", "yuìn"},
				{"ba", "pa"},
				{"bā", "pā"},
				{"bá", "pá"},
				{"bǎ", "pǎ"},
				{"bà", "pà"},
				{"bai", "pai"},
				{"bāi", "pāi"},
				{"bái", "pái"},
				{"bǎi", "pǎi"},
				{"bài", "pài"},
				{"ban", "pan"},
				{"bān", "pān"},
				{"bán", "pán"},
				{"bǎn", "pǎn"},
				{"bàn", "pàn"},
				{"bang", "pang"},
				{"bāng", "pāng"},
				{"báng", "páng"},
				{"bǎng", "pǎng"},
				{"bàng", "pàng"},
				{"bao", "pao"},
				{"bāo", "pāo"},
				{"báo", "páo"},
				{"bǎo", "pǎo"},
				{"bào", "pào"},
				{"bei", "pëi"},
				{"bēi", "p¡i"},
				{"béi", "p¢i"},
				{"běi", "p£i"},
				{"bèi", "p¤i"},
				{"ben", "pen"},
				{"bēn", "pēn"},
				{"bén", "pén"},
				{"běn", "pěn"},
				{"bèn", "pèn"},
				{"beng", "peng"},
				{"bēng", "pēng"},
				{"béng", "péng"},
				{"běng", "pěng"},
				{"bèng", "pèng"},
				{"bi", "pi"},
				{"bī", "pī"},
				{"bí", "pí"},
				{"bǐ", "pǐ"},
				{"bì", "pì"},
				{"bian", "piën"},
				{"bīan", "pi¡n"},
				{"bían", "pi¢n"},
				{"bǐan", "pi£n"},
				{"bìan", "pi¤n"},
				{"biao", "piao"},
				{"biāo", "piāo"},
				{"biáo", "piáo"},
				{"biǎo", "piǎo"},
				{"biào", "piào"},
				{"bie", "pië"},
				{"biē", "pi¡"},
				{"bié", "pi¢"},
				{"biě", "pi£"},
				{"biè", "pi¤"},
				{"bin", "pin"},
				{"bīn", "pīn"},
				{"bín", "pín"},
				{"bǐn", "pǐn"},
				{"bìn", "pìn"},
				{"bing", "ping"},
				{"bīng", "pīng"},
				{"bíng", "píng"},
				{"bǐng", "pǐng"},
				{"bìng", "pìng"},
				{"bo", "po"},
				{"bō", "pō"},
				{"bó", "pó"},
				{"bǒ", "pǒ"},
				{"bò", "pò"},
				{"bu", "pu"},
				{"bū", "pū"},
				{"bú", "pú"},
				{"bǔ", "pǔ"},
				{"bù", "pù"},
				{"ca", "cha"},
				{"cā", "chā"},
				{"cá", "chá"},
				{"cǎ", "chǎ"},
				{"cà", "chà"},
				{"cai", "chai"},
				{"cāi", "chāi"},
				{"cái", "chái"},
				{"cǎi", "chǎi"},
				{"cài", "chài"},
				{"can", "chan"},
				{"cān", "chān"},
				{"cán", "chán"},
				{"cǎn", "chǎn"},
				{"càn", "chàn"},
				{"cang", "chang"},
				{"cāng", "chāng"},
				{"cáng", "cháng"},
				{"cǎng", "chǎng"},
				{"càng", "chàng"},
				{"cao", "chao"},
				{"cāo", "chāo"},
				{"cáo", "cháo"},
				{"cǎo", "chǎo"},
				{"cào", "chào"},
				{"ce", "che"},
				{"cē", "chē"},
				{"cé", "ché"},
				{"cě", "chě"},
				{"cè", "chè"},
				{"cen", "chen"},
				{"cēn", "chēn"},
				{"cén", "chén"},
				{"cěn", "chěn"},
				{"cèn", "chèn"},
				{"ceng", "cheng"},
				{"cēng", "chēng"},
				{"céng", "chéng"},
				{"cěng", "chěng"},
				{"cèng", "chèng"},
				{"ci", "che"},
				{"cī", "chē"},
				{"cí", "ché"},
				{"cǐ", "chě"},
				{"cì", "chè"},
				{"cong", "chong"},
				{"cōng", "chōng"},
				{"cóng", "chóng"},
				{"cǒng", "chǒng"},
				{"còng", "chòng"},
				{"cou", "chou"},
				{"cōu", "chōu"},
				{"cóu", "chóu"},
				{"cǒu", "chǒu"},
				{"còu", "chòu"},
				{"cu", "chu"},
				{"cū", "chū"},
				{"cú", "chú"},
				{"cǔ", "chǔ"},
				{"cù", "chù"},
				{"cuo", "chuo"},
				{"cuō", "chuō"},
				{"cuó", "chuó"},
				{"cuǒ", "chuǒ"},
				{"cuò", "chuò"},
				{"cun", "chun"},
				{"cūn", "chūn"},
				{"cún", "chún"},
				{"cǔn", "chǔn"},
				{"cùn", "chùn"},
				{"chi", "che"},
				{"chī", "chē"},
				{"chí", "ché"},
				{"chǐ", "chě"},
				{"chì", "chè"},
				{"da", "ta"},
				{"dā", "tā"},
				{"dá", "tá"},
				{"dǎ", "tǎ"},
				{"dà", "tà"},
				{"dai", "tai"},
				{"dāi", "tāi"},
				{"dái", "tái"},
				{"dǎi", "tǎi"},
				{"dài", "tài"},
				{"dan", "tan"},
				{"dān", "tān"},
				{"dán", "tán"},
				{"dǎn", "tǎn"},
				{"dàn", "tàn"},
				{"dang", "tang"},
				{"dāng", "tāng"},
				{"dáng", "táng"},
				{"dǎng", "tǎng"},
				{"dàng", "tàng"},
				{"dao", "tao"},
				{"dāo", "tāo"},
				{"dáo", "táo"},
				{"dǎo", "tǎo"},
				{"dào", "tào"},
				{"de", "te"},
				{"dē", "tē"},
				{"dé", "té"},
				{"dě", "tě"},
				{"dè", "tè"},
				{"dei", "tëi"},
				{"dēi", "t¡i"},
				{"déi", "t¢i"},
				{"děi", "t£i"},
				{"dèi", "t¤i"},
				{"deng", "teng"},
				{"dēng", "tēng"},
				{"déng", "téng"},
				{"děng", "těng"},
				{"dèng", "tèng"},
				{"di", "ti"},
				{"dī", "tī"},
				{"dí", "tí"},
				{"dǐ", "tǐ"},
				{"dì", "tì"},
				{"dian", "tiën"},
				{"diān", "tī¡n"},
				{"dián", "tí¢n"},
				{"diǎn", "tǐ£n"},
				{"diàn", "tì¤n"},
				{"diao", "tiao"},
				{"diāo", "tiāo"},
				{"diáo", "tiáo"},
				{"diǎo", "tiǎo"},
				{"diào", "tiào"},
				{"die", "tië"},
				{"diē", "ti¡"},
				{"dié", "ti¢"},
				{"diě", "ti£"},
				{"diè", "ti¤"},
				{"ding", "ting"},
				{"dīng", "tīng"},
				{"díng", "tíng"},
				{"dǐng", "tǐng"},
				{"dìng", "tìng"},
				{"diu", "tiu"},
				{"diū", "tiū"},
				{"diú", "tiú"},
				{"diǔ", "tiǔ"},
				{"diù", "tiù"},
				{"dong", "tong"},
				{"dōng", "tōng"},
				{"dóng", "tóng"},
				{"dǒng", "tǒng"},
				{"dòng", "tòng"},
				{"dou", "tou"},
				{"dōu", "tōu"},
				{"dóu", "tóu"},
				{"dǒu", "tǒu"},
				{"dòu", "tòu"},
				{"du", "tu"},
				{"dū", "tū"},
				{"dú", "tú"},
				{"dǔ", "tǔ"},
				{"dù", "tù"},
				{"duan", "tuan"},
				{"duān", "tuān"},
				{"duán", "tuán"},
				{"duǎn", "tuǎn"},
				{"duàn", "tuàn"},
				{"dui", "tui"},
				{"duī", "tuī"},
				{"duí", "tuí"},
				{"duǐ", "tuǐ"},
				{"duì", "tuì"},
				{"duo", "tuo"},
				{"duō", "tuō"},
				{"duó", "tuó"},
				{"duǒ", "tuǒ"},
				{"duò", "tuò"},
				{"dun", "tun"},
				{"dūn", "tūn"},
				{"dún", "tún"},
				{"dǔn", "tǔn"},
				{"dùn", "tùn"},
				{"ga", "ka"},
				{"gā", "kā"},
				{"gá", "ká"},
				{"gǎ", "kǎ"},
				{"gà", "kà"},
				{"gan", "kan"},
				{"gān", "kān"},
				{"gán", "kán"},
				{"gǎn", "kǎn"},
				{"gàn", "kàn"},
				{"gang", "kang"},
				{"gāng", "kāng"},
				{"gáng", "káng"},
				{"gǎng", "kǎng"},
				{"gàng", "kàng"},
				{"gao", "kao"},
				{"gāo", "kāo"},
				{"gáo", "káo"},
				{"gǎo", "kǎo"},
				{"gào", "kào"},
				{"ge", "ke"},
				{"gē", "kē"},
				{"gé", "ké"},
				{"gě", "kě"},
				{"gè", "kè"},
				{"gei", "këi"},
				{"gēi", "k¡i"},
				{"géi", "k¢i"},
				{"gěi", "k£i"},
				{"gèi", "k¤i"},
				{"gen", "ken"},
				{"gēn", "kēn"},
				{"gén", "kén"},
				{"gěn", "kěn"},
				{"gèn", "kèn"},
				{"geng", "keng"},
				{"gēng", "kēng"},
				{"géng", "kéng"},
				{"gěng", "kěng"},
				{"gèng", "kèng"},
				{"gong", "kong"},
				{"gōng", "kōng"},
				{"góng", "kóng"},
				{"gǒng", "kǒng"},
				{"gòng", "kòng"},
				{"gou", "kou"},
				{"gōu", "kōu"},
				{"góu", "kóu"},
				{"gǒu", "kǒu"},
				{"gòu", "kòu"},
				{"gu", "ku"},
				{"gū", "kū"},
				{"gú", "kú"},
				{"gǔ", "kǔ"},
				{"gù", "kù"},
				{"gua", "kua"},
				{"guā", "kuā"},
				{"guá", "kuá"},
				{"guǎ", "kuǎ"},
				{"guà", "kuà"},
				{"guai", "kuai"},
				{"guaī", "kuaī"},
				{"guaí", "kuaí"},
				{"guaǐ", "kuaǐ"},
				{"guaì", "kuaì"},
				{"guan", "kuan"},
				{"guān", "kuān"},
				{"guán", "kuán"},
				{"guǎn", "kuǎn"},
				{"guàn", "kuàn"},
				{"guang", "kuang"},
				{"guāng", "kuāng"},
				{"guáng", "kuáng"},
				{"guǎng", "kuǎng"},
				{"guàng", "kuàng"},
				{"gui", "kui"},
				{"guī", "kuī"},
				{"guí", "kuí"},
				{"guǐ", "kuǐ"},
				{"guì", "kuì"},
				{"guo", "kuo"},
				{"guō", "kuō"},
				{"guó", "kuó"},
				{"guǒ", "kuǒ"},
				{"guò", "kuò"},
				{"gun", "kun"},
				{"gūn", "kūn"},
				{"gún", "kún"},
				{"gǔn", "kǔn"},
				{"gùn", "kùn"},
				{"ji", "ci"},
				{"jī", "cī"},
				{"jí", "cí"},
				{"jǐ", "cǐ"},
				{"jì", "cì"},
				{"jia", "cia"},
				{"jiā", "ciā"},
				{"jiá", "ciá"},
				{"jiǎ", "ciǎ"},
				{"jià", "cià"},
				{"jian", "ciën"},
				{"jiān", "ci¡n"},
				{"jián", "ci¢n"},
				{"jiǎn", "ci£n"},
				{"jiàn", "ci¤n"},
				{"jiang", "ciang"},
				{"jiāng", "ciāng"},
				{"jiáng", "ciáng"},
				{"jiǎng", "ciǎng"},
				{"jiàng", "ciàng"},
				{"jiao", "ciao"},
				{"jiāo", "ciāo"},
				{"jiáo", "ciáo"},
				{"jiǎo", "ciǎo"},
				{"jiào", "ciào"},
				{"jie", "cië"},
				{"jiē", "ci¡"},
				{"jié", "ci¢"},
				{"jiě", "ci£"},
				{"jiè", "ci¤"},
				{"jin", "cin"},
				{"jīn", "cīn"},
				{"jín", "cín"},
				{"jǐn", "cǐn"},
				{"jìn", "cìn"},
				{"jing", "cing"},
				{"jīng", "cīng"},
				{"jíng", "cíng"},
				{"jǐng", "cǐng"},
				{"jìng", "cìng"},
				{"jiu", "ciu"},
				{"jiū", "ciū"},
				{"jiú", "ciú"},
				{"jiǔ", "ciǔ"},
				{"jiù", "ciù"},
				{"ju", "cuiy"},
				{"jū", "cuīy"},
				{"jú", "cuíy"},
				{"jǔ", "cuǐy"},
				{"jù", "cuìy"},
				{"juan", "cuën"},
				{"juān", "cu¡n"},
				{"juán", "cu¢n"},
				{"juǎn", "cu£n"},
				{"juàn", "cu¤n"},
				{"jue", "cuë"},
				{"juē", "cu¡"},
				{"jué", "cu¢"},
				{"juě", "cu£"},
				{"juè", "cu¤"},
				{"jun", "cuin"},
				{"jūn", "cūin"},
				{"jún", "cúin"},
				{"jǔn", "cǔin"},
				{"jùn", "cùin"},
				{"ka", "kha"},
				{"kā", "khā"},
				{"ká", "khá"},
				{"kǎ", "khǎ"},
				{"kà", "khà"},
				{"kai", "khai"},
				{"kāi", "khāi"},
				{"kái", "khái"},
				{"kǎi", "khǎi"},
				{"kài", "khài"},
				{"kan", "khan"},
				{"kān", "khān"},
				{"kán", "khán"},
				{"kǎn", "khǎn"},
				{"kàn", "khàn"},
				{"kang", "khang"},
				{"kāng", "khāng"},
				{"káng", "kháng"},
				{"kǎng", "khǎng"},
				{"kàng", "khàng"},
				{"kao", "khao"},
				{"kāo", "khāo"},
				{"káo", "kháo"},
				{"kǎo", "khǎo"},
				{"kào", "khào"},
				{"ke", "khe"},
				{"kē", "khē"},
				{"ké", "khé"},
				{"kě", "khě"},
				{"kè", "khè"},
				{"ken", "khen"},
				{"kēn", "khēn"},
				{"kén", "khén"},
				{"kěn", "khěn"},
				{"kèn", "khèn"},
				{"keng", "kheng"},
				{"kēng", "khēng"},
				{"kéng", "khéng"},
				{"kěng", "khěng"},
				{"kèng", "khèng"},
				{"kong", "khong"},
				{"kōng", "khōng"},
				{"kóng", "khóng"},
				{"kǒng", "khǒng"},
				{"kòng", "khòng"},
				{"kou", "khou"},
				{"kōu", "khōu"},
				{"kóu", "khóu"},
				{"kǒu", "khǒu"},
				{"kòu", "khòu"},
				{"ku", "khu"},
				{"kū", "khū"},
				{"kú", "khú"},
				{"kǔ", "khǔ"},
				{"kù", "khù"},
				{"kua", "khua"},
				{"kuā", "khuā"},
				{"kuá", "khuá"},
				{"kuǎ", "khuǎ"},
				{"kuà", "khuà"},
				{"kuai", "khuai"},
				{"kuāi", "khuāi"},
				{"kuái", "khuái"},
				{"kuǎi", "khuǎi"},
				{"kuài", "khuài"},
				{"kuan", "khuan"},
				{"kuān", "khuān"},
				{"kuán", "khuán"},
				{"kuǎn", "khuǎn"},
				{"kuàn", "khuàn"},
				{"kuang", "khuang"},
				{"kuāng", "khuāng"},
				{"kuáng", "khuáng"},
				{"kuǎng", "khuǎng"},
				{"kuàng", "khuàng"},
				{"kui", "khui"},
				{"kuī", "khuī"},
				{"kuí", "khuí"},
				{"kuǐ", "khuǐ"},
				{"kuì", "khuì"},
				{"kuo", "khuo"},
				{"kuō", "khuō"},
				{"kuó", "khuó"},
				{"kuǒ", "khuǒ"},
				{"kuò", "khuò"},
				{"pa", "pha"},
				{"pā", "phā"},
				{"pá", "phá"},
				{"pǎ", "phǎ"},
				{"pà", "phà"},
				{"pai", "phai"},
				{"pāi", "phāi"},
				{"pái", "phái"},
				{"pǎi", "phǎi"},
				{"pài", "phài"},
				{"pan", "phan"},
				{"pān", "phān"},
				{"pán", "phán"},
				{"pǎn", "phǎn"},
				{"pàn", "phàn"},
				{"pang", "phang"},
				{"pāng", "phāng"},
				{"páng", "pháng"},
				{"pǎng", "phǎng"},
				{"pàng", "phàng"},
				{"pao", "phao"},
				{"pāo", "phāo"},
				{"páo", "pháo"},
				{"pǎo", "phǎo"},
				{"pào", "phào"},
				{"pei", "phëi"},
				{"pēi", "ph¡i"},
				{"péi", "ph¢i"},
				{"pěi", "ph£i"},
				{"pèi", "ph¤i"},
				{"pen", "phen"},
				{"pēn", "phēn"},
				{"pén", "phén"},
				{"pěn", "phěn"},
				{"pèn", "phèn"},
				{"peng", "pheng"},
				{"pēng", "phēng"},
				{"péng", "phéng"},
				{"pěng", "phěng"},
				{"pèng", "phèng"},
				{"pi", "phi"},
				{"pī", "phī"},
				{"pí", "phí"},
				{"pǐ", "phǐ"},
				{"pì", "phì"},
				{"pian", "phiën"},
				{"piān", "phi¡n"},
				{"pián", "phi¢n"},
				{"piǎn", "phi£n"},
				{"piàn", "phi¤n"},
				{"piao", "phiao"},
				{"piāo", "phiāo"},
				{"piáo", "phiáo"},
				{"piǎo", "phiǎo"},
				{"piào", "phiào"},
				{"pie", "phië"},
				{"piē", "phi¡"},
				{"pié", "phi¢"},
				{"piě", "phi£"},
				{"piè", "phi¤"},
				{"pin", "phin"},
				{"pīn", "phīn"},
				{"pín", "phín"},
				{"pǐn", "phǐn"},
				{"pìn", "phìn"},
				{"ping", "phing"},
				{"pīng", "phīng"},
				{"píng", "phíng"},
				{"pǐng", "phǐng"},
				{"pìng", "phìng"},
				{"po", "pho"},
				{"pō", "phō"},
				{"pó", "phó"},
				{"pǒ", "phǒ"},
				{"pò", "phò"},
				{"pou", "phou"},
				{"pōu", "phōu"},
				{"póu", "phóu"},
				{"pǒu", "phǒu"},
				{"pòu", "phòu"},
				{"pu", "phu"},
				{"pū", "phū"},
				{"pú", "phú"},
				{"pǔ", "phǔ"},
				{"pù", "phù"},
				{"qi", "chi"},
				{"qī", "chī"},
				{"qí", "chí"},
				{"qǐ", "chǐ"},
				{"qì", "chì"},
				{"qia", "chia"},
				{"qiā", "chiā"},
				{"qiá", "chiá"},
				{"qiǎ", "chiǎ"},
				{"qià", "chià"},
				{"qian", "chiën"},
				{"qiān", "chi¡n"},
				{"qián", "chi¢n"},
				{"qiǎn", "chi£n"},
				{"qiàn", "chi¤n"},
				{"qiang", "chiang"},
				{"qiāng", "chiāng"},
				{"qiáng", "chiáng"},
				{"qiǎng", "chiǎng"},
				{"qiàng", "chiàng"},
				{"qiao", "chiao"},
				{"qiāo", "chiāo"},
				{"qiáo", "chiáo"},
				{"qiǎo", "chiǎo"},
				{"qiào", "chiào"},
				{"qie", "chië"},
				{"qiē", "chi¡"},
				{"qié", "chi¢"},
				{"qiě", "chi£"},
				{"qiè", "chi¤"},
				{"qin", "chin"},
				{"qīn", "chīn"},
				{"qín", "chín"},
				{"qǐn", "chǐn"},
				{"qìn", "chìn"},
				{"qing", "ching"},
				{"qīng", "chīng"},
				{"qíng", "chíng"},
				{"qǐng", "chǐng"},
				{"qìng", "chìng"},
				{"qiong", "chiong"},
				{"qiōng", "chiōng"},
				{"qióng", "chióng"},
				{"qiǒng", "chiǒng"},
				{"qiòng", "chiòng"},
				{"qiu", "chiu"},
				{"qiū", "chiū"},
				{"qiú", "chiú"},
				{"qiǔ", "chiǔ"},
				{"qiù", "chiù"},
				{"qu", "chuiy"},
				{"qū", "chuīy"},
				{"qú", "chuíy"},
				{"qǔ", "chuǐy"},
				{"qù", "chuìy"},
				{"quan", "chuën"},
				{"quān", "chu¡n"},
				{"quán", "chu¢n"},
				{"quǎn", "chu£n"},
				{"quàn", "chu¤n"},
				{"que", "chuë"},
				{"quē", "chu¡"},
				{"qué", "chu¢"},
				{"quě", "chu£"},
				{"què", "chu¤"},
				{"qun", "chuin"},
				{"qūn", "chuīn"},
				{"qún", "chuín"},
				{"qǔn", "chuǐn"},
				{"qùn", "chuìn"},
				{"ta", "tha"},
				{"tā", "thā"},
				{"tá", "thá"},
				{"tǎ", "thǎ"},
				{"tà", "thà"},
				{"tai", "thai"},
				{"tāi", "thāi"},
				{"tái", "thái"},
				{"tǎi", "thǎi"},
				{"tài", "thài"},
				{"tan", "than"},
				{"tān", "thān"},
				{"tán", "thán"},
				{"tǎn", "thǎn"},
				{"tàn", "thàn"},
				{"tang", "thang"},
				{"tāng", "thāng"},
				{"táng", "tháng"},
				{"tǎng", "thǎng"},
				{"tàng", "thàng"},
				{"tao", "thao"},
				{"tāo", "thāo"},
				{"táo", "tháo"},
				{"tǎo", "thǎo"},
				{"tào", "thào"},
				{"te", "the"},
				{"tē", "thē"},
				{"té", "thé"},
				{"tě", "thě"},
				{"tè", "thè"},
				{"teng", "theng"},
				{"tēng", "thēng"},
				{"téng", "théng"},
				{"těng", "thěng"},
				{"tèng", "thèng"},
				{"ti", "thi"},
				{"tī", "thī"},
				{"tí", "thí"},
				{"tǐ", "thǐ"},
				{"tì", "thì"},
				{"tian", "thiën"},
				{"tiān", "thi¡n"},
				{"tián", "thi¢n"},
				{"tiǎn", "thi£n"},
				{"tiàn", "thi¤n"},
				{"tiao", "thiao"},
				{"tiāo", "thiāo"},
				{"tiáo", "thiáo"},
				{"tiǎo", "thiǎo"},
				{"tiào", "thiào"},
				{"tie", "thië"},
				{"tiē", "thi¡"},
				{"tié", "thi¢"},
				{"tiě", "thi£"},
				{"tiè", "thi¤"},
				{"ting", "thing"},
				{"tīng", "thīng"},
				{"tíng", "thíng"},
				{"tǐng", "thǐng"},
				{"tìng", "thìng"},
				{"tong", "thong"},
				{"tōng", "thōng"},
				{"tóng", "thóng"},
				{"tǒng", "thǒng"},
				{"tòng", "thòng"},
				{"tou", "thou"},
				{"tōu", "thōu"},
				{"tóu", "thóu"},
				{"tǒu", "thǒu"},
				{"tòu", "thòu"},
				{"tu", "thu"},
				{"tū", "thū"},
				{"tú", "thú"},
				{"tǔ", "thǔ"},
				{"tù", "thù"},
				{"tuan", "thuan"},
				{"tuān", "thuān"},
				{"tuán", "thuán"},
				{"tuǎn", "thuǎn"},
				{"tuàn", "thuàn"},
				{"tui", "thui"},
				{"tuī", "thuī"},
				{"tuí", "thuí"},
				{"tuǐ", "thuǐ"},
				{"tuì", "thuì"},
				{"tuo", "thuo"},
				{"tuō", "thuō"},
				{"tuó", "thuó"},
				{"tuǒ", "thuǒ"},
				{"tuò", "thuò"},
				{"tun", "thun"},
				{"tūn", "thūn"},
				{"tún", "thún"},
				{"tǔn", "thǔn"},
				{"tùn", "thùn"},
				{"xi", "shi"},
				{"xī", "shī"},
				{"xí", "shí"},
				{"xǐ", "shǐ"},
				{"xì", "shì"},
				{"xia", "shia"},
				{"xiā", "shiā"},
				{"xiá", "shiá"},
				{"xiǎ", "shiǎ"},
				{"xià", "shià"},
				{"xian", "shiën"},
				{"xiān", "shi¡n"},
				{"xián", "shi¢n"},
				{"xiǎn", "shi£n"},
				{"xiàn", "shi¤n"},
				{"xiang", "shiang"},
				{"xiāng", "shiāng"},
				{"xiáng", "shiáng"},
				{"xiǎng", "shiǎng"},
				{"xiàng", "shiàng"},
				{"xiao", "shiao"},
				{"xiāo", "shiāo"},
				{"xiáo", "shiáo"},
				{"xiǎo", "shiǎo"},
				{"xiào", "shiào"},
				{"xie", "shië"},
				{"xiē", "shi¡"},
				{"xié", "shi¢"},
				{"xiě", "shi£"},
				{"xiè", "shi¤"},
				{"xin", "shin"},
				{"xīn", "shīn"},
				{"xín", "shín"},
				{"xǐn", "shǐn"},
				{"xìn", "shìn"},
				{"xing", "shing"},
				{"xīng", "shīng"},
				{"xíng", "shíng"},
				{"xǐng", "shǐng"},
				{"xìng", "shìng"},
				{"xiong", "shiong"},
				{"xiōng", "shiōng"},
				{"xióng", "shióng"},
				{"xiǒng", "shiǒng"},
				{"xiòng", "shiòng"},
				{"xiu", "shiu"},
				{"xiū", "shiū"},
				{"xiú", "shiú"},
				{"xiǔ", "shiǔ"},
				{"xiù", "shiù"},
				{"xu", "shuiy"},
				{"xū", "shuīy"},
				{"xú", "shuíy"},
				{"xǔ", "shuǐy"},
				{"xù", "shuìy"},
				{"xuan", "shuën"},
				{"xuān", "shu¡n"},
				{"xuán", "shu¢n"},
				{"xuǎn", "shu£n"},
				{"xuàn", "shu¤n"},
				{"xue", "shuë"},
				{"xuē", "shu¡"},
				{"xué", "shu¢"},
				{"xuě", "shu£"},
				{"xuè", "shu¤"},
				{"xun", "shuin"},
				{"xūn", "shuīn"},
				{"xún", "shuín"},
				{"xǔn", "shuǐn"},
				{"xùn", "shuìn"},
				{"za", "ca"},
				{"zā", "cā"},
				{"zá", "cá"},
				{"zǎ", "cǎ"},
				{"zà", "cà"},
				{"zai", "cai"},
				{"zāi", "cāi"},
				{"zái", "cái"},
				{"zǎi", "cǎi"},
				{"zài", "cài"},
				{"zan", "can"},
				{"zān", "cān"},
				{"zán", "cán"},
				{"zǎn", "cǎn"},
				{"zàn", "càn"},
				{"zang", "cang"},
				{"zāng", "cāng"},
				{"záng", "cáng"},
				{"zǎng", "cǎng"},
				{"zàng", "càng"},
				{"zao", "cao"},
				{"zāo", "cāo"},
				{"záo", "cáo"},
				{"zǎo", "cǎo"},
				{"zào", "cào"},
				{"ze", "ce"},
				{"zē", "cē"},
				{"zé", "cé"},
				{"zě", "cě"},
				{"zè", "cè"},
				{"zei", "cëi"},
				{"zēi", "c¡i"},
				{"zéi", "c¢i"},
				{"zěi", "c£i"},
				{"zèi", "c¤i"},
				{"zen", "cen"},
				{"zēn", "cēn"},
				{"zén", "cén"},
				{"zěn", "cěn"},
				{"zèn", "cèn"},
				{"zeng", "ceng"},
				{"zēng", "cēng"},
				{"zéng", "céng"},
				{"zěng", "cěng"},
				{"zèng", "cèng"},
				{"zi", "ce"},
				{"zī", "cē"},
				{"zí", "cé"},
				{"zǐ", "cě"},
				{"zì", "cè"},
				{"zong", "cong"},
				{"zōng", "cōng"},
				{"zóng", "cóng"},
				{"zǒng", "cǒng"},
				{"zòng", "còng"},
				{"zou", "cou"},
				{"zōu", "cōu"},
				{"zóu", "cóu"},
				{"zǒu", "cǒu"},
				{"zòu", "còu"},
				{"zu", "cu"},
				{"zū", "cū"},
				{"zú", "cú"},
				{"zǔ", "cǔ"},
				{"zù", "cù"},
				{"zuan", "cuan"},
				{"zuān", "cuān"},
				{"zuán", "cuán"},
				{"zuǎn", "cuǎn"},
				{"zuàn", "cuàn"},
				{"zui", "cui"},
				{"zuī", "cuī"},
				{"zuí", "cuí"},
				{"zuǐ", "cuǐ"},
				{"zuì", "cuì"},
				{"zuo", "cuo"},
				{"zuō", "cuō"},
				{"zuó", "cuó"},
				{"zuǒ", "cuǒ"},
				{"zuò", "cuò"},
				{"zun", "cun"},
				{"zūn", "cūn"},
				{"zún", "cún"},
				{"zǔn", "cǔn"},
				{"zùn", "cùn"},
				{"zha", "ca"},
				{"zhā", "cā"},
				{"zhá", "cá"},
				{"zhǎ", "cǎ"},
				{"zhà", "cà"},
				{"zhai", "cai"},
				{"zhāi", "cāi"},
				{"zhái", "cái"},
				{"zhǎi", "cǎi"},
				{"zhài", "cài"},
				{"zhan", "can"},
				{"zhān", "cān"},
				{"zhán", "cán"},
				{"zhǎn", "cǎn"},
				{"zhàn", "càn"},
				{"zhang", "cang"},
				{"zhāng", "cāng"},
				{"zháng", "cáng"},
				{"zhǎng", "cǎng"},
				{"zhàng", "càng"},
				{"zhao", "cao"},
				{"zhāo", "cāo"},
				{"zháo", "cáo"},
				{"zhǎo", "cǎo"},
				{"zhào", "cào"},
				{"zhe", "ce"},
				{"zhē", "cē"},
				{"zhé", "cé"},
				{"zhě", "cě"},
				{"zhè", "cè"},
				{"zhei", "cëi"},
				{"zhēi", "c¡i"},
				{"zhéi", "c¢i"},
				{"zhěi", "c£i"},
				{"zhèi", "c¤i"},
				{"zhen", "cen"},
				{"zhēn", "cēn"},
				{"zhén", "cén"},
				{"zhěn", "cěn"},
				{"zhèn", "cèn"},
				{"zheng", "ceng"},
				{"zhēng", "cēng"},
				{"zhéng", "céng"},
				{"zhěng", "cěng"},
				{"zhèng", "cèng"},
				{"zhi", "ce"},
				{"zhī", "cē"},
				{"zhí", "cé"},
				{"zhǐ", "cě"},
				{"zhì", "cè"},
				{"zhong", "cong"},
				{"zhōng", "cōng"},
				{"zhóng", "cóng"},
				{"zhǒng", "cǒng"},
				{"zhòng", "còng"},
				{"zhou", "cou"},
				{"zhōu", "cōu"},
				{"zhóu", "cóu"},
				{"zhǒu", "cǒu"},
				{"zhòu", "còu"},
				{"zhu", "cu"},
				{"zhū", "cū"},
				{"zhú", "cú"},
				{"zhǔ", "cǔ"},
				{"zhù", "cù"},
				{"zhua", "cua"},
				{"zhuā", "cuā"},
				{"zhuá", "cuá"},
				{"zhuǎ", "cuǎ"},
				{"zhuà", "cuà"},
				{"zhuai", "cuai"},
				{"zhuāi", "cuāi"},
				{"zhuái", "cuái"},
				{"zhuǎi", "cuǎi"},
				{"zhuài", "cuài"},
				{"zhuan", "cuan"},
				{"zhuān", "cuān"},
				{"zhuán", "cuán"},
				{"zhuǎn", "cuǎn"},
				{"zhuàn", "cuàn"},
				{"zhuang", "cuang"},
				{"zhuāng", "cuāng"},
				{"zhuáng", "cuáng"},
				{"zhuǎng", "cuǎng"},
				{"zhuàng", "cuàng"},
				{"zhui", "cui"},
				{"zhuī", "cuī"},
				{"zhuí", "cuí"},
				{"zhuǐ", "cuǐ"},
				{"zhuì", "cuì"},
				{"zhuo", "cuo"},
				{"zhuō", "cuō"},
				{"zhuó", "cuó"},
				{"zhuǒ", "cuǒ"},
				{"zhuò", "cuò"},
				{"zhun", "cun"},
				{"zhūn", "cūn"},
				{"zhún", "cún"},
				{"zhǔn", "cǔn"},
				{"zhùn", "cùn"},

				// Permanent Exemption, a pinyin that similar, example: yang where 'yan' is detected
				{"yang", "yang"},
				{"yāng", "yāng"},
				{"yáng", "yáng"},
				{"yǎng", "yǎng"},
				{"yàng", "yàng"},

			}.OrderByDescending(x => x.Key.Length).ThenBy(x => x.Key).ToDictionary(x => x.Key, x => x.Value);

			string[] Tx = input.ToLower().Split(' ');
			string[] Fi = new string[Tx.Length];

			for (int x = 0; x < Tx.Length; x++)
			{
				int idx = 0;
				int pos = Tx[x].Length;
				int len = Tx[x].Length;
				while (len != 0)
				{
					string test;
					string temp = Tx[x].Substring(idx, len);
					if (dict.TryGetValue(temp, out test))
					{
						Fi[x] += test;
						idx = pos;
						pos = Tx[x].Length;
						len = pos - idx;
					}
					else
					{
						len--;
						pos--;
						if (idx == pos)
						{
							Fi[x] += Tx[x].Substring(pos, 1);
							idx++;
							pos = Tx[x].Length;
							len = pos - idx;
						}
					}
				}
			}

			input = "";

			for (int i = 0; i < Fi.Length; i++)
				input += Fi[i] + " ";
			
			return input.Remove(input.Length - 1);
		}

		public static string ToneToPinyin(string input)
		{
			string[] Tx = input.ToLower().Split(' ');

			input = "";

			for (int i = 0; i < Tx.Length; i++)
			{
				if (Tx[i].Contains('1'))
				{
					Tx[i] = MakeToPinyin(Tx[i], 1);
					continue;
				}
				else if (Tx[i].Contains('2'))
				{
					Tx[i] = MakeToPinyin(Tx[i], 2);
					continue;
				}
				else if (Tx[i].Contains('3'))
				{
					Tx[i] = MakeToPinyin(Tx[i], 3);
					continue;
				}
				else if (Tx[i].Contains('4'))
				{
					Tx[i] = MakeToPinyin(Tx[i], 4);
					continue;
				}
				else
				{
					Tx[i] = Regex.Replace(Tx[i], "[5]", "");
					continue;
				}
			}

			for (int i = 0; i < Tx.Length; i++)
				input = input + Tx[i] + " ";

			return input.Remove(input.Length - 1);
		}

		private static string MakeToPinyin(string input, int tone)
		{
			switch (tone)
			{
				case 1:
					if (input.Contains("ui"))
						input = input.Replace('i', 'ī');
					else if (input.Contains('a'))
						input = input.Replace('a', 'ā');
					else if (input.Contains('e'))
						input = input.Replace('e', 'ē');
					else if (input.Contains('o'))
						input = input.Replace('o', 'ō');
					else if (input.Contains('u'))
						input = input.Replace('u', 'ū');
					else if (input.Contains('i'))
						input = input.Replace('i', 'ī');
					break;
				case 2:
					if (input.Contains("ui"))
						input = input.Replace('i', 'í');
					else if (input.Contains('a'))
						input = input.Replace('a', 'á');
					else if (input.Contains('e'))
						input = input.Replace('e', 'é');
					else if (input.Contains('o'))
						input = input.Replace('o', 'ó');
					else if (input.Contains('u'))
						input = input.Replace('u', 'ú');
					else if (input.Contains('i'))
						input = input.Replace('i', 'í');
					break;
				case 3:
					if (input.Contains("ui"))
						input = input.Replace('i', 'ǐ');
					else if (input.Contains('a'))
						input = input.Replace('a', 'ǎ');
					else if (input.Contains('e'))
						input = input.Replace('e', 'ě');
					else if (input.Contains('o'))
						input = input.Replace('o', 'ǒ');
					else if (input.Contains('u'))
						input = input.Replace('u', 'ǔ');
					else if (input.Contains('i'))
						input = input.Replace('i', 'ǐ');
					break;
				case 4:
					if (input.Contains("ui"))
						input = input.Replace('i', 'ì');
					else if (input.Contains('a'))
						input = input.Replace('a', 'à');
					else if (input.Contains('e'))
						input = input.Replace('e', 'è');
					else if (input.Contains('o'))
						input = input.Replace('o', 'ò');
					else if (input.Contains('u'))
						input = input.Replace('u', 'ù');
					else if (input.Contains('i'))
						input = input.Replace('i', 'ì');
					break;
			}

			return Regex.Replace(input, "[0-9]", "");
		}
    }
}
