//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace py2km.api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("py2km.api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六王毕，四海一，蜀山兀，阿房出。覆压三百余里，隔离天日。骊山北构而西折，直走咸阳。二川溶溶，流入宫墙。五步一楼，十步一阁；廊腰缦回，檐牙高啄；各抱地势，钩心斗角。盘盘焉，囷囷焉，蜂房水涡，矗不知乎几千万落。长桥卧波，未云何龙？复道行空，不霁何虹？高低冥迷，不知西东。歌台暖响，春光融融；舞殿冷袖，风雨凄凄。一日之内，一宫之间，而气候不齐。(不知乎 一作：不知其).
        /// </summary>
        internal static string ChineseExample {
            get {
                return ResourceManager.GetString("ChineseExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HtmlContentClose {
            get {
                return ResourceManager.GetString("HtmlContentClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	&lt;span id=&quot;chinese&quot; onClick=&quot;updateSource(&apos;{4}&apos;)&quot;&gt;{0}&lt;/span&gt;&lt;br/&gt;
        ///	&lt;span&gt;{1}&lt;/span&gt;&lt;br/&gt;
        ///	&lt;span id=&quot;kwikman&quot;&gt;{2}&lt;/span&gt;&lt;br/&gt;
        ///	&lt;span id=&quot;english&quot;&gt;{3}&lt;/span&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string HtmlContentDict {
            get {
                return ResourceManager.GetString("HtmlContentDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;audio id=&quot;player&quot;&gt;
        ///	&lt;source id=&quot;mp3Source&quot; src=&quot;&quot; type=&quot;audio/mp3&quot;&gt;
        ///	Your browser does not support the audio format. Please upgrade your browser.
        ///&lt;/audio&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///function updateSource(ctrl) { 
        ///	var player=document.getElementById(&apos;player&apos;);
        ///	var sourceMp3=document.getElementById(&apos;mp3Source&apos;);
        ///
        ///	sourceMp3.src=&quot;http://translate.google.com/translate_tts?tl=zh-CN&amp;q=&quot; + ctrl;
        ///	player.load();
        ///	player.play();
        ///}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string HtmlContentJsAudio {
            get {
                return ResourceManager.GetString("HtmlContentJsAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- 
        ///	HTML5 Generator for py2km converter
        ///	py2km created by Ilham (Anime4000) @ 2015 (https://github.com/Anime4000)
        ///	With my best friend, Paan (Lc_black) @ 2015
        ///	Build with Love &lt;3
        ///	If you read this, you are awesome!
        ///--&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;/&gt;
        ///	&lt;title&gt;Super Loading...&lt;/title&gt;
        ///	&lt;style&gt;
        ///	@import url(http://fonts.googleapis.com/css?family=Open+Sans:300);
        ///
        ///	body {
        ///		background-color: #fff;
        ///		overflow: hidde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlContentLoading {
            get {
                return ResourceManager.GetString("HtmlContentLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- 
        ///	HTML5 Generator for py2km converter
        ///	py2km created by Ilham (Anime4000) @ 2015 (https://github.com/Anime4000)
        ///	With my best friend, Paan (Lc_black) @ 2015
        ///	Build with Love &lt;3
        ///	If you read this, you are awesome!
        ///--&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;/&gt;
        ///	&lt;title&gt;py2km Converter&lt;/title&gt;
        ///	&lt;style&gt;
        ///		body{padding: 0; margin: 0;font-size: 14pt;font-family: &apos;Arial Kwik Mandarin Modified&apos;, Arial, &apos;Open Sans&apos;, Ubuntu;}
        ///		#ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlContentOpen {
            get {
                return ResourceManager.GetString("HtmlContentOpen", resourceCulture);
            }
        }
    }
}
